### PR TITLE
View the fingerprint image using matplotlib.

### PR DESCRIPTION
**Pull request by jim-mckeown**
I needed to see and save the fingerprint image under Linux. Maybe others will find this useful.
- Jim

### CODE REVIEW

**Comment by FoamyGuy** [comment]
@jim-mckeown  Thanks for adding this functionality!

I think it would be best to keep the existing simpletest script as-is. This functionality could be added in a new example with something descriptive in it's name `fingerprint_picturetest.py` or something. 

If I am understanding correct, this functionality is expected to linux only as well, not on microcontrollers. If that is the case we should add a comment near the top of the file indicating that it's for Linux only and doesn't work with microcontrollers.

**Comment by jim-mckeown** [comment]
Windows users may also be interested. The only other fingerprint image
functionality I could find was the closed-source SFGDemo program. It only
runs under windows and no source code is available.

- Jim

**Comment by jim-mckeown** [comment]
I will start a new fork and pull request with the above suggestions.

**Comment by jim-mckeown** [comment]
@foamguy
I canceled this pull request and started a new fork and new pull request
with a separate example file as you suggested.

**Pull request closed without merging**
