### PR TITLE
Add Typehints

### PR DESCRIPTION
**Pull request by tekktrik**
Added typing and also disable the f-string suggestion that caused the main file to fail for pylint.  I left the files in the example folder as they are, but always was wondering what the precedent for that is, since I'm working off of the suggestions at https://circuitpython.org/contributing/library-infrastructure-issues and want to know the scope of what files that pertains too.  Thanks!

### CODE REVIEW

**Comment by tekktrik** [comment]
Moved the disable to .pylintrc

**Review by evaherrada — APPROVED** [review]
Looks good to me

**Review by kattni — CHANGES_REQUESTED** [review]
Thank you for this PR! 

Please do not edit the .pylintrc file unless instructed by one of us to do so. Editing an individual .pylintrc makes it difficult to batch update the libraries later. 

I would suggest including the `pylint: disable=` in the library for now. We added it to the pre-commit config file for example code, but not for library code. It may be worth updating the pre-commit to include the f-string disable for libraries as well, though I do not know how many libraries this is affecting currently.

**Comment by tekktrik** [comment]
Got it!  I have a few other pylint PR's I'll update as well then.  Thanks for the explanation and instruction!

**Comment by kattni** [comment]
@tekktrik Are you saying you specifically added the f-string disable on multiple libraries?

If you're running into it in any significant numbers, we need to consider updating the pre-commit config across all the libs.

**Review by evaherrada — CHANGES_REQUESTED** [review]
@tekktrik Oh yeah, Kattni's correct. My bad.

**Comment by tekktrik** [comment]
Correct, I found that to be (at least one of) the issues on the libraries I've found so far that pertain to pylint failures.  I'm new to pylint in general, so it might have been something else, but I believe on the 3 or so I've encountered it was present.

**Comment by kattni** [comment]
@tekktrik Ok. I think hold off on these PRs. I want to add the disable to all the libraries. It will take a couple of days (I think) to get that going. Please remove the disable from .pylintrc on the other repos, but do not add it to the library code. We will update the `.pre-commit-config.yaml` file, and then we'll rerun the CI on all of your PRs, and the ones that would have needed that disable will pass.

If there are other pylint failures, you're welcome to `disable` those in the code. However, if you're unsure, please ask for assistance and you can get a second opinion from a reviewer. We usually like to update the code to pass Pylint versus simply disabling, but some things will require being disabled.

**Comment by tekktrik** [comment]
Adding `# pylint: disable=consider-using-f-string` ahead of the class gives me a pre-commit error of:

`black....................................................................Passed
reuse....................................................................Passed
Check Yaml...............................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
pylint (library code)....................................................Failed
- hook id: pylint
- exit code: 2

************* Module adafruit_fingerprint
adafruit_fingerprint.py:28:0: E0012: Bad option value 'consider-using-f-string' (bad-option-value)

-----------------------------------
Your code has been rated at 9.85/10`

Any recommendations on how to properly disable it?

**Comment by kattni** [comment]
@tekktrik How does Pylint fail without the `pylint: disable=consider-using-f-string`?

**Comment by tekktrik** [comment]
Got it, thanks for the help.  I'll remove the disable from the repos' pylintrc, here's a list of the one's I've worked on I remember seeing it in (add when looking back, I looks like f-strings were the only failures) :

- https://github.com/adafruit/Adafruit_CircuitPython_Fingerprint
- https://github.com/adafruit/Adafruit_CircuitPython_ADS1x15
- https://github.com/adafruit/Adafruit_CircuitPython_GPS

**Comment by tekktrik** [comment]
So without the `# pylint: disable=`, it passes pre-commit (minus the pylint examples, but it seems that's because I'm on Windows), but will fail if I run `pylint adafruit_fingerprint.py`

>pre-commit run --all-files
black....................................................................Passed
reuse....................................................................Passed
Check Yaml...............................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
pylint (library code)....................................................Passed
pylint (examples code)...................................................Failed
- hook id: pylint_examples
- exit code: 1

Executable `/usr/bin/env` not found


>pylint adafruit_fingerprint.py
************* Module adafruit_fingerprint
adafruit_fingerprint.py:505:42: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)

-------------------------------------------------------------------
Your code has been rated at 9.97/10 (previous run: 10.00/10, -0.03)

**Comment by kattni** [comment]
@tekktrik That's because the Pylint you have installed locally is a different version than the one used by pre-commit, and therefore the one used by the libraries. You likely have a newer version installed locally. Pre-commit used 2.7.1. 

You need to use pre-commit to run Pylint if you want to ensure you're using the same version as the CI.

**Comment by kattni** [comment]
@tekktrik You can also do `pip install --force-reinstall pylint==2.7.1` (I think that's right) to force your local Pylint to match the pre-commit Pylint.

**Comment by tekktrik** [comment]
Yup that worked and confirmed with pip freeze.  With pylint==2.7.1 it now passes as it does with pre-commit.  Thanks for that, and sorry for the hassle.  I appreciate your patience!  If I want to just do a PR for the typehints, is it better to revert the changes here to match, or submit a new PR?

**Comment by kattni** [comment]
@tekktrik Revert and same PR is fine!

**Comment by tekktrik** [comment]
Updated title to reflect, reverted changes, and closed the other related PRs I had regarding linting since it didn't seem to flag anything else for them.  Thank you @kattni !! :)

**Review by kattni — APPROVED** [review]
Looks good to me! Did not test.

**Comment by kattni** [comment]
@tekktrik We're going to be updating Pylint on all the libraries. So, keep an eye out for that. You can check the `pre-commit-config.yaml` file to see which version of Pylint we're using. We're updating to 2.11.1, but it will be tomorrow or the next day when we do that. And disabling `consider-using-f-string` across the board because CircuitPython does not fully support it anyway. :)

**Comment by tekktrik** [comment]
That sounds great!  I'll stay posted here and all the channels.  Thanks again for the assistance, still getting accustomed to contributing!

**Pull request merged**
